export { default as BooleanInput } from "./BooleanInput.vue";
export { default as TextInput } from "./TextInput.vue";
export { default as NumberInput } from "./NumberInput.vue";
export { default as ListInput } from "./ListInput.vue";
export { default as ObjectInput } from "./ObjectInput.vue";
export { default as RelationInput } from "./RelationInput.vue";
export { default as FileInput } from "./FileInput.vue";
export { default as RichInput } from "./RichInput.vue";
export { default as JsonInput } from "./JsonInput.vue";
